# Publish a semver-tagged release to NPM (aka vX.Y.Z).
#
name: "NPM Publish"

on:
  push:
    tags: v[0-9]+.[0-9]+.[0-9]+
  release:
    types: [created]

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository.
      uses: actions/checkout@v2

    - name: Setup the node environment.
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 14 # use the most recent LTS version
        registry-url: https://registry.npmjs.org/

    - name: Install the package with a clean slate.
      run: npm ci

    - name: Publish the package to NPM.
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
